language: java
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
    - jorge.bernal.professional@gmail.com
script:
#Test unitario y de integracion en perfil DEV, con cobertura
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

# SONAR
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jorge-bernal-github -Dsonar.login=$SONAR_TOKEN

# Deploy https://api-demo.herokuapp.com/swagger-ui.html
deploy:
  provider: heroku
  app: jorge-bernal-api-demo
  api_key:
    secure: $HEROKU_TOKEN
  on:
    branch: master
